version: '3.1'

services:
  mongo:
    image: mongo:7.0.2
    restart: always
    ports:
      - 27017:27017

    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS

  app:
    build: .
    container_name: metric_microservice
    env_file: ./.env

    depends_on:
      - mongo
    links:
      - mongo

    ports:
      - $API_PORT:$DOCKER_PORT
    environment:
      - DEV_ENV=development
      - MONGODB_URI=$MONGODB_URI_DEV
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port $DOCKER_PORT --reload
